### ISSUE TITLE
Inference code for a prompt + single image as input

### ISSUE THREAD

**Issue by arnaudocus** [ylingfeng/FGVP#1]
Hello 👋 

I just found out your repository, nice work !
I was wondering if there was a quick way to do some inference on a single image with a prompt to assess the results on randomly picked images 😃 

Thanks !

**Comment by ylingfeng** [comment]
Thanks for your interest! Now we have added a corresponding script to infer a single image at https://github.com/ylingfeng/FGVP/tree/main?tab=readme-ov-file#inference-single-image.
