### ISSUE TITLE
how to use grid-wise keypoints to prompt SAM 

### ISSUE THREAD

**Issue by Tzx11** [ylingfeng/FGVP#2]
Hello，I'm interested in your work.
I wonder how to use grid-wise keypoints to prompt SAM model?
Looking forward to your reply.

**Comment by ylingfeng** [comment]
We appreciate your interest! To prompt the SAM model with grid-wise keypoints, you can follow the first script [here](https://github.com/ylingfeng/FGVP?tab=readme-ov-file#inference-single-image), which is a simple demo for inferring one image with provided captions. Detailed parameter settings for grid-wise keypoints can be found in [SAM](https://github.com/facebookresearch/segment-anything/blob/main/notebooks/automatic_mask_generator_example.ipynb).
